config/routes.rb
Rails.application.routes.draw do
  get 'tweets/index'
  resources :tweets, only: %i[index create destroy]
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all.sort_by(&:created_at).reverse
    @tweet = Tweet.new
  end

  def create
    @tweets = Tweet.all.sort_by(&:created_at).reverse
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to tweets_path
    else
      render 'index'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    redirect_to tweets_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AliTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Ali Tweet v2.1</h1>
<% if @tweet.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being twitted:
    </h2>
    <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @tweet, local: true do |form| %>
  <p>
    <%= form.label :tweet %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit 'Tweet' %>
  </p>
<% end %>

<h1>What's Up?</h1>
<div>
<% @tweets.each do |tweet| %>
  <pre>
  Posted date: <%= tweet.created_at.strftime("%F %T") %> | <%= link_to 'Delete', tweet_path(tweet), method: :delete, data: { confirm: 'Are you sure?' } %>


  <%= tweet.content %> <br>
  </pre>
  <hr>
<% end %>
</div>